dataset:
  dataset_id: sagecontinuum/INQUIRE-Benchmark-small
  splits: "validation+test"
  directory: data/inquire_benchmark/raw
  export_images: true

embedding:
  model_id: openai/clip-vit-base-patch32
  batch_size: 64
  directory: data/inquire_benchmark/emb

vectordb:
  type: qdrant.hnsw
  params:
    url: localhost
    collection_name: benchmark
    metric: ip
    m: 64

search:
  topk: 10
  queries_file: benchmark/queries.txt

update:
  add_count: 50
  delete_count: 30
