dataset:
  dataset_id: sagecontinuum/INQUIRE-Benchmark-small
  splits: "validation+test"
  directory: data/inquire_benchmark/raw
  export_images: true

embedding:
  model_id: openai/clip-vit-base-patch32
  batch_size: 64
  directory: data/inquire_benchmark/emb

container:
  image: "milvusdb/milvus:v2.6.3"
  ports:
    "19530": "19530"
    "9091": "9091"

vectordb:
  type: milvus
  params:
    url: localhost
    port: "19530"
    collection_name: benchmark
    index_type: IVF_FLAT
    metric: l2
    batch_size: 1000

search:
  topk: 10
  queries_file: benchmark/queries.txt

update:
  add_count: 50
  delete_count: 30
